<a href="https://colab.research.google.com/github/RasheedHuma/RasheedHuma/blob/main/segment_transcripts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transcript Segmentation Notebook

This notebook:
1. Loads a CSV where each row is one transcript.
2. Creates a unique transcript identifier.
3. Splits `main text` into segments and explodes into one row per segment.
4. Saves the result back to Google Drive.

In [ ]:
import pandas as pd
import re
import hashlib
from typing import List

## 1) Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 2) Set the path to your CSV in Drive

In [ ]:
# Read in transcript data
INPUT_CSV_PATH = '/content/drive/MyDrive/AD Content Analysis/Data compilation and cleaning/AD_News_All_Unsegmented.csv'

CHANNEL_COL = 'Channel'
TEXT_COL = 'Body'

df = pd.read_csv(INPUT_CSV_PATH)
df.count() # Count values in each column

Unnamed: 0    1279
Filename      1279
Channel       1248
Show          1248
Date          1279
Words         1279
Body          1279
dtype: int64

In [ ]:
# See how many rows don't have channel name
na_count = df['Channel'].isna().sum()
print("Rows that will be removed:", na_count)

Rows that will be removed: 31

In [ ]:
# Remove rows without channel name
df.dropna(subset=['Channel'], inplace=True)
df.count()

Unnamed: 0    1248
Filename      1248
Channel       1248
Show          1248
Date          1248
Words         1248
Body          1248
segments      1248
dtype: int64

In [ ]:
# Create ID column
df.rename(columns={df.columns[0]: "Transcript_ID"}, inplace=True)
df.head(10)

,Transcript_ID,Filename,Channel,Show,Date,Words,Body,segments
0,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025",3232,"RAFAEL ROMO, CNN CORRESPONDENT: Wednesday, eig...","[RAFAEL ROMO, CNN CORRESPONDENT: Wednesday, ei..."
1,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025",3285,"WOLF BLITZER, CNN HOST: Bovino spoke about the...","[WOLF BLITZER, CNN HOST: Bovino spoke about th..."
2,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",8811,"(COMMERCIAL BREAK)\nMARTHA MACCALLUM, FOX NEWS...","[MARTHA MACCALLUM, FOX NEWS ANCHOR: All right...."
3,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",7949,"SEAN HANNITY, FOX NEWS HOST: And tonight, with...","[SEAN HANNITY, FOX NEWS HOST: And tonight, wit..."
4,4,Copy of 19 Suspected TDA Members Detained In A...,Fox News,@ NIGHT,"December 18, 2024",7409,"KAT TIMPF, FOX NEWS CONTRIBUTOR: Thanks to Joe...","[KAT TIMPF, FOX NEWS CONTRIBUTOR: Thanks to Jo..."
5,5,Copy of 20+ Dem Governors Join Biden In _Crisi...,Fox News,@ NIGHT,"July 3, 2024",7392,"(COMMERCIAL BREAK)\nGREG GUTFELD, FOX NEWS CHA...","[GREG GUTFELD, FOX NEWS CHANNEL HOST: Out of t..."
7,7,"Copy of 48 Hours - Deputy Spivey on Trial, CBS...",CBS News,News Transcripts Cbs 48 Hours,"January 11, 2025",7062,"(ANNOUNCEMENT)\n(Graphic onscreen: Houston, Te...","[(ANNOUNCEMENT)\n(Graphic onscreen: Houston, T..."
8,8,Copy of 48 Hours - Rodney Alcala_ The Killing ...,CBS News,News Transcripts Cbs 48 Hours,"June 1, 2024",6435,(ANNOUNCEMENT)\n(Graphic onscreen: One of the ...,[(ANNOUNCEMENT)\n(Graphic onscreen: One of the...
9,9,Copy of 49ers' Ricky Pearsall To Miss Multiple...,Fox News,THE GREG GUTFELD SHOW,"September 3, 2024",3071,(COMMERCIAL BREAK)\n(BEGIN VIDEO CLIP)\nUNIDEN...,[(BEGIN VIDEO CLIP)\nUNIDENTIFIED MALE: A stor...
10,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,"MIKE BOYLAN, STORM CHASER: Actually June, righ...","[MIKE BOYLAN, STORM CHASER: Actually June, rig..."

In [ ]:
# Create and run function to split transcripts into segments
CHANNEL_MARKERS = {
    'CNN': r'\(commercial\s+break\)',
    'FOX NEWS': r'\(commercial\s+break\)',
    'ABC NEWS': r'\((ANNOUNCEMENTS|COMMERCIAL\s+BREAK)\)',
    'CBS NEWS': r'\(ANNOUNCEMENTS\)'
}

def split_into_segments(channel: str, text: str) -> List[str]:
    if text is None or (isinstance(text, float) and pd.isna(text)):
        return []
    text = str(text)
    if channel is None or (isinstance(channel, float) and pd.isna(channel)):
        return [text.strip()] if text.strip() else []

    ch = str(channel).strip().upper()
    pattern = CHANNEL_MARKERS.get(ch)
    if not pattern:
        return [text.strip()] if text.strip() else []

    parts = re.split(pattern, text, flags=re.IGNORECASE)
    parts = [p.strip() for p in parts if p and p.strip()]
    return parts

df['segments'] = df.apply(lambda r: split_into_segments(r[CHANNEL_COL], r[TEXT_COL]), axis=1)

seg_df = df.explode('segments', ignore_index=True)
seg_df = seg_df[seg_df['segments'].notna() & (seg_df['segments'].astype(str).str.strip() != '')].copy()

seg_df['segment_number'] = seg_df.groupby('Transcript_ID').cumcount() + 1

seg_df[TEXT_COL] = seg_df['segments']
seg_df = seg_df.drop(columns=['segments'])

# Count number of words in each segment
seg_df['segment_words'] = seg_df[TEXT_COL].astype(str).str.split().str.len()

# Drop segments with fewer than 10 words
seg_df = seg_df[seg_df['segment_words'] >= 50].copy()

print('Original transcripts:', len(df))
print('Segmented rows:', len(seg_df))
seg_df.head(50)

Original transcripts: 1248
Segmented rows: 5180

,Transcript_ID,Filename,Channel,Show,Date,Words,Body,segment_number,segment_words
0,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025",3232,"RAFAEL ROMO, CNN CORRESPONDENT: Wednesday, eig...",1,183
1,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025",3232,BOLDUAN: This just in. We are now -- we've now...,2,1149
2,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025",3232,"SIDNER: All right. On our radar for you today,...",3,1890
4,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025",3285,"WOLF BLITZER, CNN HOST: Bovino spoke about the...",1,1368
5,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025",3285,"BLITZER: All right, back to our breaking news,...",2,1267
6,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025",3285,"BLITZER: New this morning, ""The New York Times...",3,646
7,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",8811,"MARTHA MACCALLUM, FOX NEWS ANCHOR: All right. ...",1,1390
8,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",8811,"MACCALLUM: I mean, this one's getting a lot of...",2,1362
9,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",8811,"MACCALLUM: So, his new claims around the, quot...",3,1940
10,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",8811,MACCALLUM: Bit of a setback on this Friday aft...,4,4111
11,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",7949,"SEAN HANNITY, FOX NEWS HOST: And tonight, with...",1,3870
12,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",7949,HANNITY: All right. So did Kamala Harris just ...,2,2751
13,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",7949,HANNITY: All right. We're now just 15 days awa...,3,1035
14,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",7949,"HANNITY: Pretty shocking, Nathan Wade appears ...",4,287
15,4,Copy of 19 Suspected TDA Members Detained In A...,Fox News,@ NIGHT,"December 18, 2024",7409,"KAT TIMPF, FOX NEWS CONTRIBUTOR: Thanks to Joe...",1,4098
16,4,Copy of 19 Suspected TDA Members Detained In A...,Fox News,@ NIGHT,"December 18, 2024",7409,(BEGIN VIDEO CLIP)\nTRUMP: We're trying to hel...,2,1354
17,4,Copy of 19 Suspected TDA Members Detained In A...,Fox News,@ NIGHT,"December 18, 2024",7409,GALLAGHER: Waiting for the mamas and the papas...,3,1373
18,4,Copy of 19 Suspected TDA Members Detained In A...,Fox News,@ NIGHT,"December 18, 2024",7409,"GALLAGHER: Back with the ""NIGHTCAP"" crew: Kevi...",4,578
19,5,Copy of 20+ Dem Governors Join Biden In _Crisi...,Fox News,@ NIGHT,"July 3, 2024",7392,"GREG GUTFELD, FOX NEWS CHANNEL HOST: Out of ti...",1,4201
20,5,Copy of 20+ Dem Governors Join Biden In _Crisi...,Fox News,@ NIGHT,"July 3, 2024",7392,HUNT: Breaking tonight as you look at that hur...,2,1532
21,5,Copy of 20+ Dem Governors Join Biden In _Crisi...,Fox News,@ NIGHT,"July 3, 2024",7392,"HUNT: Back to tonight's top story, the questio...",3,1286
22,5,Copy of 20+ Dem Governors Join Biden In _Crisi...,Fox News,@ NIGHT,"July 3, 2024",7392,"HUNT: We are back with the ""NIGHTCAP"" crew: Ma...",4,365
23,7,"Copy of 48 Hours - Deputy Spivey on Trial, CBS...",CBS News,News Transcripts Cbs 48 Hours,"January 11, 2025",7062,"(ANNOUNCEMENT)\n(Graphic onscreen: Houston, Te...",1,7062
24,8,Copy of 48 Hours - Rodney Alcala_ The Killing ...,CBS News,News Transcripts Cbs 48 Hours,"June 1, 2024",6435,(ANNOUNCEMENT)\n(Graphic onscreen: One of the ...,1,6435
25,9,Copy of 49ers' Ricky Pearsall To Miss Multiple...,Fox News,THE GREG GUTFELD SHOW,"September 3, 2024",3071,(BEGIN VIDEO CLIP)\nUNIDENTIFIED MALE: A story...,1,973
26,9,Copy of 49ers' Ricky Pearsall To Miss Multiple...,Fox News,THE GREG GUTFELD SHOW,"September 3, 2024",3071,(BEGIN VIDEO CLIP)\nUNIDENTIFIED MALE: Five mo...,2,1063
27,9,Copy of 49ers' Ricky Pearsall To Miss Multiple...,Fox News,THE GREG GUTFELD SHOW,"September 3, 2024",3071,(BEGIN VIDEO CLIP)\nUNIDENTIFIED MALE: We've g...,3,1000
29,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,"MIKE BOYLAN, STORM CHASER: Actually June, righ...",1,4083
30,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,COOPER: I mentioned the Congressional Black Ca...,2,1349
31,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,"COOPER: Well, just moments ago, Patty Murray, ...",3,1668
32,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,COOPER: Despite staying mostly out of the publ...,4,723
33,10,Copy of 6 House Dems Say Biden Should Leave Ra...,CNN,ANDERSON COOPER 360 DEGREES,"July 8, 2024",8364,COOPER: Tropical Depression Beryl is moving th...,5,533
34,11,"Copy of 60 MINUTES for November 9, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"November 9, 2025",7335,CECILIA VEGA (voiceover): American farmers hav...,1,309
35,11,"Copy of 60 MINUTES for November 9, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"November 9, 2025",7335,THE FAMILY FARM\nCECILIA VEGA (voiceover): Ame...,2,2225
36,11,"Copy of 60 MINUTES for November 9, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"November 9, 2025",7335,"60 MINUTES for November 9, 2025, CBS\nCOLLATER...",3,2156
37,11,"Copy of 60 MINUTES for November 9, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"November 9, 2025",7335,THE INDOMITABLE MARGARET ATWOOD\nJON WERTHEIM:...,4,2478
38,11,"Copy of 60 MINUTES for November 9, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"November 9, 2025",7335,ANNOUNCER: The Last Minute of 60 MINUTES is sp...,5,158
40,12,"Copy of 60 MINUTES, April 27, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"April 27, 2025",6982,"SHARYN ALFONSI (voiceover): Tonight, you will ...",1,311
41,12,"Copy of 60 MINUTES, April 27, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"April 27, 2025",6982,"NIH\nSHARYN ALFONSI: Earlier this month, a Tru...",2,2066
42,12,"Copy of 60 MINUTES, April 27, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"April 27, 2025",6982,EVIDENCE\nCECILIA VEGA: Evidence has emerged t...,3,2291
43,12,"Copy of 60 MINUTES, April 27, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"April 27, 2025",6982,THE LAND OF DECLINING SONS\nJON WERTHEIM: The ...,4,2074
44,12,"Copy of 60 MINUTES, April 27, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"April 27, 2025",6982,ANNOUNCER: The Last Minute of 60 MINUTES is sp...,5,231
46,13,"Copy of 60 MINUTES, August 31, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 31, 2025",7071,NORAH O`DONNELL (voiceover): What has this 76-...,1,351
47,13,"Copy of 60 MINUTES, August 31, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 31, 2025",7071,CHINA`S SPIES\nNORAH O`DONNELL: According to t...,2,2120
48,13,"Copy of 60 MINUTES, August 31, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 31, 2025",7071,"ST. MARY`S\n60 MINUTES, August 31, 2025, CBS\n...",3,2262
49,13,"Copy of 60 MINUTES, August 31, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 31, 2025",7071,SOUNDS OF CAJUN COUNTRY\nJON WERTHEIM: The ide...,4,2216
50,13,"Copy of 60 MINUTES, August 31, 2025, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 31, 2025",7071,NORAH O`DONNELL: 60 MINUTES will be off for th...,5,113
52,14,"Copy of 60 MINUTES, August 4, 2024, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 4, 2024",7650,WOMAN #1: You`re going to go in there.\nSHARYN...,1,259
53,14,"Copy of 60 MINUTES, August 4, 2024, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 4, 2024",7650,MASTER OF THE MIND\nSHARYN ALFONSI: Anyone who...,2,2617
54,14,"Copy of 60 MINUTES, August 4, 2024, CBS.PDF",CBS News,News Transcripts Cbs 60 Minutes,"August 4, 2024",7650,SHARYN ALFONSI: The human brain contains a hun...,3,2374

In [ ]:
seg_df.describe()

       Transcript_ID         Words  segment_number  segment_words
count    5180.000000   5180.000000     5180.000000    5180.000000
mean      632.005019   7509.992471        3.576834    1411.448649
std       368.640281   3070.756079        3.018781    1119.735721
min         0.000000    103.000000        1.000000      50.000000
25%       297.750000   6775.000000        2.000000     724.000000
50%       636.000000   7531.000000        3.000000    1159.000000
75%       942.000000   8253.000000        4.000000    1763.000000
max      1278.000000  19183.000000       19.000000   16625.000000

In [ ]:
#Some of the segments are still very long (15k words). Let's break them down into smaller than 1000 words segments.
import re
import math

def split_long_segments(text, max_words=1000):
    if not text or not str(text).strip():
        return []

    text = re.sub(r'\s+', ' ', str(text).strip())
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', text) if s.strip()]

    if not sentences:
        return [text]

    total_words = sum(len(s.split()) for s in sentences)

    # do nothing if already small
    if total_words <= max_words:
        return [text]

    # number of chunks
    n_chunks = math.ceil(total_words / max_words)
    target = total_words / n_chunks

    chunks = []
    current = []
    current_words = 0

    for sent in sentences:
        sent_words = len(sent.split())

        # don't exceed max_words
        if current and current_words + sent_words > max_words:
            chunks.append(" ".join(current))
            current = [sent]
            current_words = sent_words
            continue

        # balance chunk sizes
        if current and current_words >= target:
            chunks.append(" ".join(current))
            current = [sent]
            current_words = sent_words
            continue

        current.append(sent)
        current_words += sent_words

    if current:
        chunks.append(" ".join(current))

    return chunks

In [ ]:
seg_df['segment_words'] = seg_df[TEXT_COL].str.split().str.len()

seg_df['split_parts'] = seg_df.apply(
    lambda r: split_long_segments(r[TEXT_COL], max_words=1000)
    if r['segment_words'] > 1000
    else [r[TEXT_COL]],
    axis=1
)

seg_df = seg_df.explode('split_parts', ignore_index=True)

seg_df[TEXT_COL] = seg_df['split_parts']
seg_df = seg_df.drop(columns=['split_parts'])

seg_df['segment_words'] = seg_df[TEXT_COL].str.split().str.len()

# drop small segments
seg_df = seg_df[seg_df['segment_words'] >= 100].copy()

# reset index (optional but clean)
seg_df = seg_df.reset_index(drop=True)

In [ ]:
seg_df['segment_words'].describe()

count    9899.000000
mean      737.407011
std       177.760957
min       100.000000
25%       623.000000
50%       766.000000
75%       873.000000
max      1000.000000
Name: segment_words, dtype: float64

In [ ]:
#Create a segment unique ID
seg_df["Segment_ID"] = range(1, len(seg_df) + 1)

In [ ]:
#Identify AD related segments

import re

KEYWORDS = {
    "alzheimer",
    "dementia",
    "cognitive decline",
    "cognitive impairment",
    "memory loss",
}

pattern = "|".join(re.escape(word) for word in KEYWORDS)

seg_df["AD"] = (
    seg_df["Body"]
    .fillna("")
    .str.lower()
    .str.contains(pattern, regex=True)
    .astype(int)
)

In [ ]:
seg_df.columns

Index(['Transcript_ID', 'Filename', 'Channel', 'Show', 'Date', 'Words', 'Body',
       'segment_number', 'segment_words', 'Segment_ID', 'AD'],
      dtype='object')

In [ ]:
seg_df = seg_df[["Segment_ID", "Transcript_ID", "Filename", "Channel", "Show", "Date", "Body", "segment_words","AD"]].copy()

In [ ]:
seg_df.head(30)

,Segment_ID,Transcript_ID,Filename,Channel,Show,Date,Body,segment_words,AD
0,1,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025","RAFAEL ROMO, CNN CORRESPONDENT: Wednesday, eig...",183,0
1,2,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025",BOLDUAN: This just in. We are now -- we've now...,575,0
2,3,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025","So in reality, how far does a round of strikes...",574,0
3,4,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025","SIDNER: All right. On our radar for you today,...",956,0
4,5,0,Copy of $18 Billion Powerball Jackpot Won On C...,CNN,News Central,"December 26, 2025","TIM ANDREWS: It may shorten your life, but you...",934,1
5,6,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025","WOLF BLITZER, CNN HOST: Bovino spoke about the...",688,0
6,7,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025",I have heard from our business owners in the c...,680,1
7,8,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025","BLITZER: All right, back to our breaking news,...",674,0
8,9,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025","Many people do. It seems crazy, but the FBI ha...",593,0
9,10,1,Copy of ' New York Times ' Sues Pentagon ; New...,CNN,THE SITUATION ROOM,"December 4, 2025","BLITZER: New this morning, ""The New York Times...",646,0
10,11,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025","MARTHA MACCALLUM, FOX NEWS ANCHOR: All right. ...",696,0
11,12,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",The initial information that I received is tha...,694,0
12,13,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025","MACCALLUM: I mean, this one's getting a lot of...",684,0
13,14,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025","This is also posted by James Comey. Boy, he fi...",678,0
14,15,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025","MACCALLUM: So, his new claims around the, quot...",964,1
15,16,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025","You know, there might have been an attempt to ...",972,1
16,17,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",MACCALLUM: Bit of a setback on this Friday aft...,826,0
17,18,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",That's the first thing we have to do. We also ...,827,0
18,19,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",HUTSON: Yes. Some of them have reached out to ...,833,0
19,20,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",WEIS: You said you've been asking for money fo...,840,0
20,21,2,"Copy of 11 NOLA Jail Inmates Escaped, At Least...",Fox News,THE STORY WITH MARTHA MACCALLUM,"May 18, 2025",So it's going to be an interesting postmortem....,785,0
21,22,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024","SEAN HANNITY, FOX NEWS HOST: And tonight, with...",974,0
22,23,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",It's not about policies as that that last pers...,992,0
23,24,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024","HANNITY: Yeah. You know, it's so funny. The --...",984,0
24,25,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",Did you see the reaction from the left about t...,920,0
25,26,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",HANNITY: All right. So did Kamala Harris just ...,920,0
26,27,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024","HORACE COOPER, PROJECT 21 CHAIRMAN: Well, what...",919,1
27,28,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024","What are your thoughts? JOE CONCHA, FOX NEWS C...",912,0
28,29,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024",HANNITY: All right. We're now just 15 days awa...,531,0
29,30,3,Copy of 15 Days Until The Election.PDF,Fox News,FOX HANNITY,"October 21, 2024","So I think right now, I feel very confident th...",504,0

## 3) Save output back to Google Drive

In [ ]:
OUTPUT_CSV_PATH = '/content/drive/MyDrive/AD Content Analysis/Data compilation and cleaning/segmented_transcripts_06252026.csv'
seg_df.to_csv(OUTPUT_CSV_PATH, index=False)
print('Saved to:', OUTPUT_CSV_PATH)

Saved to: /content/drive/MyDrive/AD Content Analysis/Data compilation and cleaning/segmented_transcripts_06252026.csv